export const EXPO_PUBLIC_ONBOARDED_KEY = process.env.EXPO_PUBLIC_ONBOARDED_KEY ?? "";
export const EXPO_PUBLIC_SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL ?? "";
export const EXPO_PUBLIC_SUPABASE_KEY = process.env.EXPO_PUBLIC_SUPABASE_KEY ?? "";
